import { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"
import Containar from "@/components/common/containar"
import GoBack from "@/components/common/goBack"
import Header from "@/components/common/header"
import ja from "@/shared/i18n/ja"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ja">
            <body className={inter.className}>
                <Header title={ja.header.title} />
                <GoBack />
                <Containar>{children}</Containar>
            </body>
        </html>
    )
}
